# First Play
- name: Play - Handle Files in all hosts
  hosts: all
  tasks:
  - name: all host are identified with a file
    copy:
      content: My family is {{ ansible_os_family }}
      dest: /family.txt
      mode: '777'

# Second play
- name: Play - for Alpines Nodejs app
  hosts: app_group
  tasks:
  - name: NodeJs is installed
    apk:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    loop:
    - nodejs
    - nodejs-npm
  - name: app directory is created
    file:
      path: /node-app
      state: directory
  - name: app is installed
    template:
      src: app.js.j2
      dest: /node-app/app.js
  - name: app dependencies file is copied
    copy:
      src: package.json
      dest: /node-app/package.json
  - name: app dependencies are installed
    npm:
      path: /node-app
      state: present
      production: true
  - name: Install forever (to run Node.js app).
    npm: name=forever global=yes state=present
  
  - name: Check list of Node.js apps running.
    command: forever list
    register: forever_list
    changed_when: false

  - name: Start example Node.js app.
    command: forever start /node-app/app.js
    when: "forever_list.stdout.find('/node-app/app.js') == -1"

# Third play
- name: Play - install nginx on loadbalancer
  hosts: loadbalancer
  tasks:
    - name: Ensure Nginx is installed and it is the latest version
      command: apk --no-cache add nginx

    # VVVV EORROR HERE VVVV

    - name: Start Nginx if not already running
      service:
        name: nginx
        state: started
      ignore_errors: true
      register: nginx_status

    - name: Copy the Nginx config file and restart nginx
      copy:
        src: ./nginx.cfg
        dest: /etc/nginx/sites-available/nginx.cfg
     
    - name: Create symlink
      file:
        src: /etc/nginx/sites-available/nginx.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Restart nginx
      service:
        name: nginx
        state: restarted